{% set version = "1.1.1" %}

package:
  name: conda-build-all
  version: {{ version }}

source:
    fn: conda-build-all_v{{ version }}.tar.gz
    url: https://github.com/conda-tools/conda-build-all/archive/v{{version}}.tar.gz
    sha256: e67b97d7af971807df4b18bac2f1ade5514fdf48cff427d1d87432e4a3330733

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - conda-build-all = conda_build_all.cli:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - gitpython
    - conda >=4.2
    - conda-build >=1.21.7
    - anaconda-client
    - mock

test:
  imports:
    - conda_build_all
  commands:
    - conda build-all --version

about:
  license: BSD 3-clause
  license_file: LICENSE
  home: https://github.com/conda-tools/conda-build-all
  summary: conda build-all is a conda subcommand which allows multiple distributions to be built (and uploaded) in a single command

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - marqh
    - isuruf
