travis:
  secure:
    BINSTAR_TOKEN: VzbSi7zmicJh/RGky40pYm+r16ULw0QqB318etAPumxFf5/ioQ+8kJ2CPYSZ0b0rvUvXXSu1W4W/EzH8DoPF7FHGvgt6JIfKoJsIyW5how3MBt95Il/mjZJ2mBGrpwyukGRuAvQYQ3Yf8UeVMcaF7z8jmwIBbDbR29fereT91vDYwU1DuvSM5EgfsKC7twrhR4IxIKU/ulR6YeBFOPlNSqFnK7y12M5nj5JW2GbXUNUi6Z0Gl0HcMt6Wa7O9gx2wQgP1t8DBnTxFAdXGuZVccwzNxkiUYwWCT31svKlkVKm9TNAxP93oBysFrGdwC18DH+iinJ6ke85B8OrQJmxieXFlg5uecImpC3R6Da0qLOm8qTIOE5dfqciA3PCRKgc6o2OxeLNsiVhVIDkAMtQLUj3pXtGILiNlfIF5cuK5nljBVcEfQt2A+ZImZxFFdyiO4yzl0r7QjiPgVm4ZBdjtQ1aTLUSAxKOWYQsNVl0CSE+YCgMKkbCsTHQ1/peNzmIz4fqfITEcwVstIGI003TVhMwHHUlpwFMIhHnN5NG/ZE79qUwzFlJSvI/iDFrOmZaC1TNmcbuWjV4SZe85bdwDi1lhqofau5/8AO+gScJ461dHXqL5SDZOPEz0IbG8GKx77NP+F16YU/7NNKHSZQZaRzbzwacf5CZMPz87uWSnZGM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
